[env]
RUST_TEST_THREADS = { value = "1" }

[registry]
default = "gitea"

[registries.gitea]
index = "sparse+https://git.uncollap.se/api/packages/Uncollapse/cargo/" # Sparse index

[net]
git-fetch-with-cli = true
